name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-and-package.yml
    permissions:
      contents: write
    with:
      modules: >-
        ["SmokeAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        res/SmokeAPI.config.json

      config: Release
